CFLAGS=-Wall -pedantic -std=c11 -I ../utils/ -L ../lib/ -g
LIBS=-lutils -lcurl

all:			test_pageio

test_pageio:	test_pageio.c
				gcc $(CFLAGS) test_pageio.c $(LIBS) -o $@

clean:
				rm -f *.o test_pageio